from Tkinter import *

def inity(frame):
    Chat = Frame(frame,height=10,width=100)
    Chat.pack(side=BOTTOM)
    B1 = Button(Chat,text='ChatFrame',height=10,width=100)
    B1.pack()
    E1 = Entry(Chat,width=100)
    E1.pack(side=BOTTOM)

    RightMenu = Frame(frame,width=64,height=30)
    RightMenu.pack(side=RIGHT)
    MainDisp = Frame(frame)
    MainDisp.pack(side=RIGHT)
    But = Button(MainDisp,text='Main display')
    But.pack(side=LEFT)
    item1 = Frame(RightMenu)
    item1.pack(side=TOP)
    B1 = Button(item1, text="Big Rule Book",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item1, text="Magic Lores",width=10,height=2)
    B2.pack(side=RIGHT)
    item2 = Frame(RightMenu)
    item2.pack(side=TOP)
    B1 = Button(item2, text="Army Books",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item2, text="Saved Armies",width=10,height=2)
    B2.pack(side=RIGHT)
    item3 = Frame(RightMenu)
    item3.pack(side=TOP)
    B1 = Button(item3, text="To Battle!",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item3, text="Tournaments",width=10,height=2)
    B2.pack(side=RIGHT)
    item4 = Frame(RightMenu)
    item4.pack(side=TOP)
    B1 = Button(item4, text="Campaign",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item4, text="Rankings",width=10,height=2)
    B2.pack(side=RIGHT)
    item5 = Frame(RightMenu)
    item5.pack(side=TOP)
    B1 = Button(item5, text="Friends",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item5, text="Options",width=10,height=2)
    B2.pack(side=RIGHT)
    B2.pack(side=RIGHT)
    item6 = Frame(RightMenu)
    item6.pack(side=TOP)
    B1 = Button(item6, text="Maps",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item6, text="Create Scenario",width=10,height=2)
    B2.pack(side=RIGHT)
    item7 = Frame(RightMenu)
    item7.pack(side=TOP)
    B1 = Button(item7, text="Blacksmith",width=10,height=2)
    B1.pack(side=LEFT)
    B2 = Button(item7, text="",width=10,height=2)
    B2.pack(side=RIGHT)
    B2.pack(side=RIGHT)

root = Tk()
frame = Frame(root, width=1024)
frame.pack()
menuBar = Menu(frame)

inity(frame)

newTask = Menu(menuBar, tearoff=0)
newTask.add_separator()
newTask.add_command(label="Exit", command=root.quit)
menuBar.add_cascade(label="File", menu=newTask)

root.config(menu=menuBar)
root.mainloop()
